# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;
  boot.kernelModules = [ "amdgpu" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/012f1bbf-60bb-49d0-a3df-972ceb8b28d7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/b503ce43-ec96-465e-991d-cca52ca9c067";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/702E-7E73";
      fsType = "vfat";
    };

  fileSystems."/files" =
    { device = "/dev/disk/by-uuid/848ba4fe-0a5a-4278-b7e7-78a2ddb7a831";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptfiles".device = "/dev/disk/by-uuid/c4728935-37a2-4872-b394-c1583677fb98";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0f5c36ec-0ab5-4d2f-b8b4-9a368fd07eac"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
